spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=USER_ID # USER_ID ??? ????? ??? ??
      routes:
          - id: user-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
            filters:
              - AuthorizationHeaderFilter

          - id: mission-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/missions/**

          - id: created-mission-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/created-missions/**


jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8000