
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=USER_ID
      routes:
          - id: user-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
            filters:
              - AuthorizationHeaderFilter

          - id: mission-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/missions/**
              - Path=/api/weather/**
            filters:
              - AuthorizationHeaderFilter

          - id: created-mission-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/created-missions/**
            filters:
              - AuthorizationHeaderFilter

          - id: board-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/boards/**
            filters:
              - AuthorizationHeaderFilter

          - id: coupon-service
            uri: http://localhost:8085
            predicates:
              - Path=/api/coupons/**
            filters:
              - AuthorizationHeaderFilter
          
          - id: auth-service
            uri: http://localhost:8087
            predicates:
              - Path=/api/signup,/api/users/signup,/api/v1/sign-in,/api/v1/logout,/oauth2/authorization/kakao



jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8000