spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=USER_ID
      routes:
          - id: user-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
            filters:
              - AuthorizationHeaderFilter

          - id: mission-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/missions/**
              - Path=/api/weather/**
            filters:
              - AuthorizationHeaderFilter

          - id: created-mission-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/created-missions/**
            filters:
              - AuthorizationHeaderFilter

          - id: board-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/boards/**
            filters:
              - AuthorizationHeaderFilter

          - id: coupon-service
            uri: http://localhost:8085
            predicates:
              - Path=/api/coupons/**
            filters:
              - AuthorizationHeaderFilter


jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8000