spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=USER_ID
      routes:
          - id: user-service
            uri: http://user-service:8081
            predicates:
              - Path=/api/users/**
            filters:
              - AuthorizationHeaderFilter

          - id: mission-service
            uri: http://mission-service:8082
            predicates:
              - Path=/api/missions/**
              - Path=/api/weather/**
            filters:
              - AuthorizationHeaderFilter

          - id: created-mission-service
            uri: http://created-mission-service:8083
            predicates:
              - Path=/api/created-missions/**
            filters:
              - AuthorizationHeaderFilter

          - id: board-service
            uri: http://board-service:8084
            predicates:
              - Path=/api/boards/**
            filters:
              - AuthorizationHeaderFilter

          - id: coupon-service
            uri: http://coupon-service:8085
            predicates:
              - Path=/api/coupons/**
            filters:
              - AuthorizationHeaderFilter
          
          - id: auth-service
            uri: http://auth-service:8086
            predicates:
              - Path=/api/signup
              - Path=/api/v1/sign-in
              - Path=/api/v1/logout
              - Path=/oauth2/authorization/kakao


jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8000