# PersistentVolumeClaim 설정 (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual  # PV와 동일하게 설정

---

# PersistentVolume 설정 (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 4Gi  # PVC와 일치해야 함
  accessModes:
    - ReadWriteOnce  # PVC와 동일한 접근 모드
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # PVC와 일치해야 함
  hostPath:
    path: "/mnt/data"  # 노드의 로컬 경로

---

# Jenkins Deployment 설정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      #serviceAccountName: jenkins
      #securityContext:
      #  fsGroup: 1000
      initContainers:
      - name: volume-mount-fix
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home && chown 1000:1000 /var/run/docker.sock"]  # Docker 소켓 권한 추가
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
      containers:
      - name: jenkins
        image: kangwoobin/jenkins-with-docker:latest
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock 



---

# Jenkins Service 설정
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000  # 원하는 NodePort 지정
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 32001
  selector:
    app: jenkins
