spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

ai:
  endpoints:
    mission-auth: ${AI_ENDPOINTS_MISSION_AUTH}
    weather: ${AI_ENDPOINTS_WEATHER}
    local: ${AI_LOCAL}
server:
  port: 8082
