apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-service
  template:
    metadata:
      labels:
        app: check-service
    spec:
      nodeSelector:
        node-role: backend
      containers:
        - name: check-service
          image: kangwoobin/check-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: check-service
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: check-service
