apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-service
  template:
    metadata:
      labels:
        app: common-service
    spec:
      nodeSelector:
        node-role: backend
      containers:
        - name: common-service
          image: kangwoobin/common-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: common-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: common-service
