apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-service
  template:
    metadata:
      labels:
        app: coupon-service
    spec:
      nodeSelector:
        node-role: backend
      containers:
        - name: coupon-service
          image: kangwoobin/coupon-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-service
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: coupon-service
